# Load and Prepare Data

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from google.colab import files
uploaded = files.upload()

Saving player-groups (6).xlsx to player-groups (6).xlsx

In [3]:
df = pd.read_excel('player-groups (6).xlsx')

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 13 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   number   12 non-null     int64
 1   season   12 non-null     object
 2   team     12 non-null     object
 3   apps     12 non-null     int64
 4   min      12 non-null     int64
 5   goals    12 non-null     int64
 6   assists  12 non-null     int64
 7   sp90m    12 non-null     float64
 8   kp90     12 non-null     float64
 9   xG       12 non-null     float64
 10  xA       12 non-null     float64
 11  xG90     12 non-null     float64
 12  xA90     12 non-null     float64
dtypes: float64(6), int64(5), object(2)
memory usage: 1.3+ KB

In [8]:
df.head(15)

,number,season,team,apps,min,goals,assists,sp90m,kp90,xG,xA,xG90,xA90
0,1,2025/2026,Manchester City,36,2797,2,4,0.90,1.48,2.70,5.25,0.09,0.17
1,2,2024/2025,Manchester City,33,2660,4,4,1.08,1.79,4.79,5.00,0.16,0.17
2,3,2023/2024,Manchester City,33,2599,6,9,1.18,2.25,4.10,8.53,0.14,0.30
3,4,2022/2023,Manchester City,34,2194,4,5,1.03,1.23,2.26,3.92,0.09,0.16
4,5,2021/2022,Manchester City,35,2865,8,4,1.51,1.85,7.77,6.57,0.24,0.21
5,6,2020/2021,Manchester City,26,2080,2,6,1.21,1.17,3.60,4.82,0.16,0.21
6,7,2019/2020,Manchester City,34,2020,6,7,2.32,2.27,7.42,6.31,0.33,0.28
7,8,2018/2019,Manchester City,36,2851,7,7,1.96,2.24,8.20,8.63,0.26,0.27
8,9,2017/2018,Manchester City,35,1500,6,4,1.50,1.80,4.53,3.06,0.27,0.18
9,10,2016/2017,Monaco,37,2829,8,9,1.91,1.91,5.71,7.41,0.18,0.24
10,11,2015/2016,Monaco,32,2246,7,1,1.64,1.72,6.51,3.86,0.26,0.15
11,12,2014/2015,Monaco,32,2290,9,3,1.34,1.81,6.32,5.60,0.25,0.22

In [9]:
# Rename columns to business-friendly names
df = df.rename(columns={
    "number": "ID",
    "season": "Season",
    "team": "Club",
    "apps": "Matches Played",
    "min": "Minutes Played",
    "goals": "Goals Scored",
    "assists": "Assists Made",
    "sp90m": "Goal Contributions per 90",
    "kp90": "Key Passes per 90",
    "xG": "Expected Goals",
    "xA": "Expected Assists",
    "xG90": "Expected Goals per 90",
    "xA90": "Expected Assists per 90"
})

# View updated structure
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   ID                         12 non-null     int64
 1   Season                     12 non-null     object
 2   Club                       12 non-null     object
 3   Matches Played             12 non-null     int64
 4   Minutes Played             12 non-null     int64
 5   Goals Scored               12 non-null     int64
 6   Assists Made               12 non-null     int64
 7   Goal Contributions per 90  12 non-null     float64
 8   Key Passes per 90          12 non-null     float64
 9   Expected Goals             12 non-null     float64
 10  Expected Assists           12 non-null     float64
 11  Expected Goals per 90      12 non-null     float64
 12  Expected Assists per 90    12 non-null     float64
dtypes: float64(6), int64(5), object(2)
memory usage: 1.3+ KB

In [10]:
df.head()

,ID,Season,Club,Matches Played,Minutes Played,Goals Scored,Assists Made,Goal Contributions per 90,Key Passes per 90,Expected Goals,Expected Assists,Expected Goals per 90,Expected Assists per 90
0,1,2025/2026,Manchester City,36,2797,2,4,0.90,1.48,2.70,5.25,0.09,0.17
1,2,2024/2025,Manchester City,33,2660,4,4,1.08,1.79,4.79,5.00,0.16,0.17
2,3,2023/2024,Manchester City,33,2599,6,9,1.18,2.25,4.10,8.53,0.14,0.30
3,4,2022/2023,Manchester City,34,2194,4,5,1.03,1.23,2.26,3.92,0.09,0.16
4,5,2021/2022,Manchester City,35,2865,8,4,1.51,1.85,7.77,6.57,0.24,0.21

# Player Scouting Report
Player: Bernardo Silva

Season Range: 2017/18 – 2025/26
Club: Manchester City
Dataset Type: Performance, Creativity & Expected Metrics

1️⃣ Executive Summary

Bernardo Silva is a highly adaptable, tactically intelligent attacking midfielder with sustained elite-level creative output across multiple seasons.

Key findings:

Multiple performance peaks (not a single anomaly season)
Strong creative consistency (kp90 & xA trends)
Efficient alignment between expected and actual output
Low volatility in attacking metrics
Demonstrates role flexibility without major performance drop-off

Overall profile:
Elite hybrid creator with long-term stability and tactical adaptability.

2️⃣ Creative Output Analysis
Metrics Used:
Key Passes per 90 (kp90)
Expected Assists (xA)
Expected Assists per 90 (xA90)
Assists
Findings:

Peak Creative Volume:

2018/19 – 2019/20 (highest kp90 period)
2023/24 (strong resurgence)

Best Creative Efficiency Season:

2023/24 (xA90 = 0.30)
Highest assist output (9 assists)
Interpretation:
Early career = high-volume chance creator
Mid-career = tactical adjustment period
2023/24 = creative peak resurgence
Recent seasons = moderate but stable output

Conclusion:
Creativity remains elite, with evidence of sustained high-level playmaking across career phases.

3️⃣ Expected vs Actual Performance (Efficiency Analysis)
Goals vs xG
Generally aligned with expected output
Occasional overperformance seasons (notably 2023/24)
No long-term finishing inefficiency
Assists vs xA
Strong alignment
Creative output is structurally consistent
Minimal reliance on luck

Conclusion:
Bernardo is a statistically stable performer with predictable efficiency and no major deviation from expected models.

4️⃣ Playing Time & Productivity
Analysis:
Minutes played vary across seasons
Productivity per 90 remains relatively stable
High performance occurs in both high-minute and moderate-minute seasons
Key Insight:

Performance is more influenced by role positioning than total minutes.

Conclusion:
He is workload-resilient and does not require extreme playing time to maintain effectiveness.

5️⃣ Overall Attacking Contribution Trend

Across seasons:

Strong early hybrid attacking profile (goals + assists)
Tactical shift toward more creative responsibilities
2023/24 represents full attacking resurgence
No structural long-term decline visible in dataset
Career Pattern:
Rise to creative peak (2018–2020)
Role adjustment phase (2020–2022)
Creative resurgence (2023/24)
Stabilization phase (2024–2026)

Conclusion:
His career reflects evolution, not regression.

6️⃣ Strengths

✔ Elite creativity (high kp90 historically)
✔ Strong expected assist metrics
✔ Tactical adaptability
✔ Consistent efficiency vs xG/xA
✔ Multi-season peak performance capability
✔ Stable attacking contribution model

7️⃣ Development / Monitoring Areas
Slight decline in key pass volume in most recent seasons
Goal output lower in recent years compared to early peak
Monitor whether role shift continues toward deeper midfield function

These are trends, not weaknesses.

8️⃣ Overall Player Profile

Type:
Hybrid Creative Midfielder / Advanced Playmaker

Risk Profile:
Low volatility
High consistency
Predictable output

Value Characteristics:

Tactical flexibility
System compatibility
Long-term reliability
Strong expected-metric alignment
9️⃣ Final Scouting Verdict

Bernardo Silva demonstrates:

Sustained elite creative ability
Multiple peak performance phases
Strong efficiency relative to expected metrics
Tactical adaptability without performance collapse
No evidence of sharp long-term decline

He profiles as a high-value, system-adaptable, intelligence-driven attacking midfielder with proven multi-year consistency.